a3qz/hag

gui.c
gui.h
main.c

to use the new dialog prompt, call `gui_prompt(prompt, options)` wherever you want to. `prompt` is a string representing the question you want to ask, such as "Win the game? (y or n)"
`options` is a string listing each of the options the user can pick, such as "yn".
The function returns what option the user chose, as a single character.

Added dialog prompts

---

enemy.c
enemy_rulebook.c
enemy_rulebook.h
floor.c
gui.c
main.c
main.h
map.c
map.h

Boss BAMFs away every 3 hits. I want it to summon snakes. We need to incorporate glyphs somehow.

Old Hag Boss

---

Makefile
enemy.c
enemy_rulebook.c
gui.c
item.c
key.c
main.c
map.c

Fixed comments

---

LICENSE.txt

It's some random modified MIT license with beer thing that was in a github gist.
Thoughts, @a3qz and @dontworrybhappy ?

Add beer license

---

src/args.c
src/args.h
src/floor.c
src/main.c

Added `--help`, and `--seed` arguments (which fixes #75). If more flags are needed later, they shouldn't be too difficult to add.

Add command-line args

---

README.md
src/main.c

Issue #76 
Added simple log output of the available controls when a player presses `ESC`. Updated README.

Add babby controls manual

---

src/flavortext.c
src/flavortext.h
src/main.c

This makes it easy to solve #72. Basically, we just need somebody who can write well to fill out the flavortext.c file.

Added framework for flavortext

---

Makefile

Debian/ubuntu seemed to fail without this

Remove werror

---

src/flavortext.c

Hey! did you want something like this? let me know! I can revise it or change it or you can assign it to someone else if someone else has a much better one.
fixed issue #72

added flavour text

---

src/enemy_rulebook.c
src/main.c
src/player.c

Has room for improvement, this is pure random.  Might want to do something like, roll for each stat then take the avg

Make attack damage random, not just based on stats

---

src/item.c
src/item.h
src/key.c
src/main.c
src/player.c
src/player.h

Gives players a chance to identify the stat affected by drinking the potion.
My stab at issue #69

Added I(nspect) command, to inspect a potion

---

src/main.c

Fixes #111 without the floor.c changes

Default case for invalid button presses

---

src/core/main.c
src/world/map.c

Fixes #125 and #126 because @dontworrybhappy ignored us assigning her.

Fix lighting issues

---

src/ui/key.c
src/world/floor.c

This removes the first floor ladder. As per #73, this greatly changes the speed running strategy. Unfortunately this move will be highly controversial. The community may die off. However, I feel this change is important for game integrity.

Remove the first floor ladder

---

src/world/map.c

Fixed difference between x and y for lighting

---

src/logic/item.c

fix plurals

---

src/logic/enemy_rulebook.c

fixed #138
- reorders the code
- removes empty elses

fix enemy movement code issues

---

contributing.md

basic contributing file

---

src/core/controls.h
src/core/main.c

Added fight to death

---

src/core/main.c

Added floor preloading

---

src/core/args.c
src/core/args.h
src/core/demo.c
src/core/demo.h
src/core/main.c

Implements #132, allowing a game to be recorded. This will allow for proof of completing the game, among other things.

Demo Record + Replay

---

src/core/args.c
src/core/args.h
src/core/demo.c
src/core/demo.h
src/core/main.c

* Added demo
* Added default demo file

Demo Record + Replay (#150)

---

src/core/main.c

Dying dying death death
